### ISSUE TITLE
Readme_Update Required

### ISSUE THREAD

**Issue by Meetjain1** [ashutoshgithubs/iemhacks_DEV-G#115]
**Describe the changes that you want to make in the documentation**
Small update in readme file by adding animated emojis in place of static emojis with some allignment fixing and adding some sections to readme to make it more attracting 

**Significance of the changes made**
Will attract more and more contributors to contribute to this project .

![devg2](https://github.com/ashutoshgithubs/iemhacks_DEV-G/assets/133582566/d303abc5-1966-4085-a94c-02a8766c2c78)

![devg1](https://github.com/ashutoshgithubs/iemhacks_DEV-G/assets/133582566/f1b3c51c-78f3-4015-ab6d-0eaadef090ad)

**Comment by maha-sachin** [comment]
hey @Meetjain1 ,
You can start working on this task. Please keep us updated on your progress. Once you have a working solution, we will review it. If everything looks good, we'll proceed with merging it.

Thank you!

**Comment by Meetjain1** [comment]
> hey @Meetjain1 , You can start working on this task. Please keep us updated on your progress. Once you have a working solution, we will review it. If everything looks good, we'll proceed with merging it.
> 
> Thank you!

Sure @maha-sachin
