### ISSUE TITLE
Implement Google Signup Feature in React

### ISSUE THREAD

**Issue by ashutoshgithubs** [ashutoshgithubs/iemhacks_DEV-G#2]
I want to enhance Dev-G user experience by providing the option for users to sign up using their Google accounts. This issue will cover the implementation of the Google signup feature in React application.

### Tasks:

1. **Integration with Google OAuth**: Implement OAuth authentication with Google to allow users to sign up using their Google accounts.

2. **User Interface Changes**: Update the signup page to include the option for users to sign up with Google.

3. **Error Handling**: Implement appropriate error handling for cases such as account already exists, network errors, etc.

### Acceptance Criteria:

- Users can sign up using their Google accounts.

- The signup process seamlessly integrates with the existing authentication flow.
- Proper error messages are displayed to users in case of failures

**Comment by anuni03** [comment]
I would like to do this task as I have previously done a task like this in one of my projects. Please assign this task to me under GGSOC 2024

**Comment by Yaswanthtoga** [comment]
Hi @ashutoshgithubs , i have already started yesterday itself on this issue. I have connected with you regarding to missed files as well. Can you please assign it to me under GSSOC'24. 
Thanks

**Comment by MrCoser** [comment]
I have implemented OAuth authentication before in one of my projects, so I believe I can make this as well. Please assign it to me under GSSOC'24.

**Comment by ashutoshgithubs** [comment]
Hello @Yaswanthtoga, are you interested to work on this issue?

**Comment by anuni03** [comment]
Hello, Why did you unassign this issue. I am interested in it and i was working on this issue

**Comment by ashutoshgithubs** [comment]
@anuni03 Due to some issue at my end, I had unassigned. Now its okay. You can start working on this issue.

**Comment by ashutoshgithubs** [comment]
@anuni03 any work progress on this issue??

**Comment by ashutoshgithubs** [comment]
> @anuni03 any work progress on this issue??

Hey @anuni03 , can you please respond with your progress??

**Comment by ashutoshgithubs** [comment]
> > @anuni03 any work progress on this issue??
> 
> Hey @anuni03 , can you please respond with your progress??

As you are not active, So you are unassigned from this task.

**Comment by MrCoser** [comment]
@ashutoshgithubs sir, if it's possible, can you assign this to me under GSSOC'24 ? I know certain web development skills and I have integrated Google authentication on one of my earlier projects. So, I can work on this.
