### ISSUE TITLE
Enchancement : Hover Effect on Cards

### ISSUE THREAD

**Issue by devmusiczz** [ashutoshgithubs/iemhacks_DEV-G#22]
![image](https://github.com/ashutoshgithubs/iemhacks_DEV-G/assets/114563397/34c5dc23-acd2-4f36-b2fb-8bc905c8c3a3)

The Hover Effect on cards can make the website more user-interactive and visually appealing.
Can you assign this task to me under GSSOC 2024?

**Comment by gitshanmukh123** [comment]
can I also work on the same issue  as a part of GSSOC24  ,I would like to give it nice dark theme tailwind css with responsive and neat tailwind css

**Comment by ashutoshgithubs** [comment]
Hi @devmusiczz , you can start the work for this issue and all the best!

**Comment by Manishar55** [comment]
Hello, @ashutoshgithubs 
I go through the project and I would like to work on this project
can you please assign this issue to me so that I can add some hover effect on the cards to make it more beautiful.
