### ISSUE TITLE
ADDING new SECTION for USER advices and  informing bugs 

### ISSUE THREAD

**Issue by gitshanmukh123** [ashutoshgithubs/iemhacks_DEV-G#24]
I would like to create a seperate page or section for  advices and other suggestions section which is more admirable for websites like these so that if any developer finds any bug or improvements in your website ,then he or she can directly contact to you , as I will link a  api to your email account ,if you provide me ur email details after assigning me the project.ONCE IF HE OR SHE CLICK ON SUBMIT THEN YOU WILL GET AN EMAIL SHOWING ALL THESE INFORMATIONS.(SHOWIN IN 3rD IMAGE)

![Screenshot_10-5-2024_13522_localhost](https://github.com/ashutoshgithubs/iemhacks_DEV-G/assets/160143412/0cea3737-a046-4026-942c-9a79572e7aef)
![Screenshot_10-5-2024_141142_localhost](https://github.com/ashutoshgithubs/iemhacks_DEV-G/assets/160143412/4c12a655-f7b0-4a22-a001-d6e351478f37)

![Screenshot_10-5-2024_14143_mail google com](https://github.com/ashutoshgithubs/iemhacks_DEV-G/assets/160143412/a987db32-7980-4c2e-be19-4eeffd1b455a)

THERE in the description the website users can share some suggestions and share their email address to connect with you and also I could PROVIDE A LITTLE MORE IMPROVEMENTS .

 I BELIEVE THIS WOULD TAKE UR WEBSITE A BIT MORE HEAD THAN OTHERS,OR INSTEAD IF YOU ARE NOT WILLING TO SHARE EMAIL DETAILS THEN I COULD CREATE ONE FOR YOU AND PROVIDE YOU THE DETAILS. 

THIS WOULD LOOK LIKE THE SCREENSHOT ABOVE  AND I WILL MAKE SOME CHANGES ACCORDING TO THE NEEDS OF YOUR WEBSITE

IF YOU LIKE MY NEW FEATURE ,KINDLY ASSIGN IT TO ME UNDER  GSSOC'2024 .waiting for your response

**Comment by gitshanmukh123** [comment]
Can you assign me this issue under gssoc 24

**Comment by BipulRahi** [comment]
### @gitshanmukh123 if u visit the live website and see carefully ```the feature u want to implement ``` is already there but because of css properties its button shifted as   i have two devices and when i give a look through both of my devices of different screen size then the button is appear on 
> small screen (upto 14' ) but 
>partially visible on large screen (>14') as it get shifted towards bottom

###  so may it matter of css 

## I created a new Issue for this please have a look on that issue #32 

<br/>

![ahsu](https://github.com/ashutoshgithubs/iemhacks_DEV-G/assets/91903346/33cd4ff9-5ef7-4b4c-b11a-584a5e56a529)

**Comment by gitshanmukh123** [comment]
sorry for it , can you assign me that issue under #32 and close this issue

**Comment by ashutoshgithubs** [comment]
This feature is already there in the website under "Facing an issue?" button. So, I'm closing it.
