### ISSUE TITLE
Adding page for DevOps section in catalogue

### ISSUE THREAD

**Issue by PranotiPD** [ashutoshgithubs/iemhacks_DEV-G#25]
Currently on clicking on DevOps section in catalogue we are getting 404

![Screenshot (751)](https://github.com/ashutoshgithubs/iemhacks_DEV-G/assets/97724414/f5adaf6d-526c-42d8-a4f5-974fb5ec7fcc)

So want to add courses to this section as other sections.

I would like to work on this issue.

Contribution for Gssoc'24.

**Comment by BipulRahi** [comment]
@PranotiPD  as per my review of the code , its is not about adding new page it about the adding new data in the databse through the website as the components made in raect so it just render the information fetched by the database it not about page missing it about not enough data in the category of devops
> @PranotiPD plzz go with categories schema to getting the structure of the data  in db models file 
###  @ashutoshgithubs plz confirm is it page miss or data insufficiency so we can think upon this issue

**Comment by ashutoshgithubs** [comment]
@BipulRahi @PranotiPD its not a page miss. If you create a course under this section, it will appear.

**Comment by Yashc885** [comment]
i would like to resolve this issue

**Comment by ashutoshgithubs** [comment]
Hello mates, its not an issue. If you create a course under DevOps it will appear under this category. So I'm closing this issue.
