### ISSUE TITLE
Fixing the Home Page Alignment.

### ISSUE THREAD

**Issue by prafulnigam** [ashutoshgithubs/iemhacks_DEV-G#26]
![image](https://github.com/ashutoshgithubs/iemhacks_DEV-G/assets/78497704/0d68f839-f6e9-4ec3-afa2-e9eb4ef0a3db)

**Comment by prafulnigam** [comment]
I am Praful Nigam. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by ashutoshgithubs** [comment]
Hi @prafulnigam , this issue has been already addressed in #6 . Please try some other issue.

**Comment by Jamir2412** [comment]
@prafulnigam Can you please assign this issue to me..?

**Comment by ashutoshgithubs** [comment]
This issues has been already solved under #6 . So I'm closing this issue. Keep contributing...
