### ISSUE TITLE
Fixing the alignment of the landing page

### ISSUE THREAD

**Issue by mdrehan369** [ashutoshgithubs/iemhacks_DEV-G#29]
![Screenshot from 2024-05-10 23-55-36](https://github.com/ashutoshgithubs/iemhacks_DEV-G/assets/121730065/e344594a-d5f2-482f-9bc6-5dc47e6c1a2e)
Hello Sir,
I found that the landing page is not centered whenever the user lands on it.
**Please assign me this issue to work on under GSSOC 2024.**

**Comment by ashutoshgithubs** [comment]
@mdrehan369 This has been already addressed in issue number #6 . Try contributing in some other issues and if you find some other issues, raise them and get assigned.

**Comment by Jamir2412** [comment]
@mdrehan369 Can you please assign this issue to me..?

**Comment by KavyaBS123** [comment]
Hey @ashutoshgithubs can you please assign this issue to me I would like to work on it.

**Comment by ashutoshgithubs** [comment]
Hey everyone, thanks for exploring the project. But this issue has addressed already in #6 . Please find some features enhancement/bugs/issue and raise them in issue section.
