### ISSUE TITLE
" FACING AN ISSUE " BUTTON NOT VISIBLE ON LARGE SCREEN 

### ISSUE THREAD

**Issue by BipulRahi** [ashutoshgithubs/iemhacks_DEV-G#32]
### because of css properties the ' Facing an Issue '  button shifted as i have two devices and when i give a look through both of my devices of different screen  size then the button  is appear on small screen <br/> `(upto 14' )` but partially visible on large screen <br/> `(>14')` as it get shifted  towards bottom 
>  button name - [ FACING AN ISSUE]
<br/>

![ahsu](https://github.com/ashutoshgithubs/iemhacks_DEV-G/assets/91903346/33cd4ff9-5ef7-4b4c-b11a-584a5e56a529)

**Comment by gitshanmukh123** [comment]
can You assign me this issue under GSSOC2024

**Comment by ashutoshgithubs** [comment]
@gitshanmukh123 you can start your work. I have assigned this issue.

**Comment by gitshanmukh123** [comment]
thank you  for assigning ,I will start my work.

**Comment by Yashc885** [comment]
i would like to resolve this issue

**Comment by ashutoshgithubs** [comment]
Work completed.
