### ISSUE TITLE
Not getting redirected to About us page when clicked on link while user is signed in 

### ISSUE THREAD

**Issue by PranotiPD** [ashutoshgithubs/iemhacks_DEV-G#43]
When the user is logged in, if they try to click on "About Us " section it is not getting redirected to About Us section but getting redirected to user profile page.

Let me know if it is valid issue. @BipulRahi 

I would like to work on it.

Please assign it to me.

**Comment by ashutoshgithubs** [comment]
Hi @PranotiPD , Good Observation! Appreciated!!
I have kept the About Section under protected Route by mistake. But it has no significance here. Just release it from protection. I'm assigning to you.
