### ISSUE TITLE
Correcting spelling errors on the Home page

### ISSUE THREAD

**Issue by soham-hecker** [ashutoshgithubs/iemhacks_DEV-G#45]
I would like to be assigned the task under GSSOC'24 to rectify spelling errors I found on the Home Page. 
For eg. "catalogue" was written as "catlog".

![IMG_20240511_221538](https://github.com/ashutoshgithubs/iemhacks_DEV-G/assets/146989532/01be71e1-6691-4ff2-bb1b-8bba3d394406)

**Comment by ashutoshgithubs** [comment]
Hi @soham-hecker “Catalogue” is the preferred spelling in British English and some other varieties of English. “Catalog” is the preferred spelling in American English. So, I don't find any issue in this. But thanks for your time. Keep contributing...

**Comment by ashutoshgithubs** [comment]
Not an issue.
