### ISSUE TITLE
Feature : Scroll to Top Button for Improved User Experience

### ISSUE THREAD

**Issue by antriksh-9** [ashutoshgithubs/iemhacks_DEV-G#49]
On  [website](https://edtech-dev-g-frontend.vercel.app/home) a back-to-top button isn't present which is a common website feature.

I propose adding a "Scroll to Top" button that becomes visible as the user scrolls down the website page.
Tapping this button would smoothly scroll the user back to the top, providing a convenient and efficient way to navigate lengthy content.

**Comment by antriksh-9** [comment]
Hey @ashutoshgithubs , I want to work on this issue.
Please assign me under GSSoC '24.

**Comment by ashutoshgithubs** [comment]
Hi @antriksh-9 , You are assigned this work.
