### ISSUE TITLE
Missing CONTRIBUTING.md File in Repository

### ISSUE THREAD

**Issue by suhanipaliwal** [ashutoshgithubs/iemhacks_DEV-G#50]
The repository currently lacks a CONTRIBUTING.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A CONTRIBUTING.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.

Could you please assign this issue to me under GSSOC 24.

**Comment by ashutoshgithubs** [comment]
Hi @suhanipaliwal , I was also planning to have a separate file for CONTRIBUTING Guidelines. I have enclosed these guidelines in LEARN.md in repo. Please take the reference from there and work on it. You are assigned this task.
