### ISSUE TITLE
Reducing Code Duplication

### ISSUE THREAD

**Issue by Abh-I-seK** [ashutoshgithubs/iemhacks_DEV-G#59]
I noticed some code sections in <b>src/pages/TopHome.jsx</b> seem to be repeated. 

I think we could create a separate component to handle this logic.
Could you please assign this issue to me under GSSOC 24.

**Comment by Abh-I-seK** [comment]
To be more specific I want to turn the following code into a component

![Screenshot 2024-05-13 234136](https://github.com/ashutoshgithubs/iemhacks_DEV-G/assets/134422863/78c49b73-b558-4849-8dab-3efd60660219)

I wanted to kindly request an update on the progress of this issue. Your assistance is greatly appreciated.

**Comment by SiddhantBarman-PageUp** [comment]
hey @Abh-I-seK please assign this issue to me under GSSOC-2024

**Comment by ashutoshgithubs** [comment]
Hi @Abh-I-seK Thanks for your contributions.
