### ISSUE TITLE
Home page alignment issue 

### ISSUE THREAD

**Issue by BipulRahi** [ashutoshgithubs/iemhacks_DEV-G#6]
the Home page is little bit shifted toward left on large screen

**Comment by Chetan8299** [comment]
I would like to fix this issue, so please assign it to me.

**Comment by gitshanmukh123** [comment]
As I was very fond of responsive frontend ,can you please assign this issue to me ?? I will try to solve it as soon as possible
,I want to contribute to it from GSSOC24

**Comment by Krish3914** [comment]
like I have a strong base of frontend ,can you please assign this issue to me!! 
I will definately try to solve it as soon as possible.
I really want to contribute to it from GSSOC'24

**Comment by ashutoshgithubs** [comment]
Hi @thecurioussailor,
Comment below this issue first to get it assigned, then further process will be done.. We have to maintain the guidelines..

**Comment by thecurioussailor** [comment]
@BipulRahi @ashutoshgithubs Alrighty! Assign me the above issue.

**Comment by ashutoshgithubs** [comment]
@thecurioussailor , Thanks for your contribution. Your PR has been merged successfully. You should not limit your valuable contributions here....Keep exploring projects and keep contributing. All the best!

**Comment by ashutoshgithubs** [comment]
This issue is resolved. So, I am closing this issue. Thanks for your time and contribution.
