### ISSUE TITLE
Title font overlapping on landing page.

### ISSUE THREAD

**Issue by Maxcillius** [ashutoshgithubs/iemhacks_DEV-G#62]
- Heading title text overlaps at around ~724px width.

![Screenshot from 2024-05-13 11-39-48](https://github.com/ashutoshgithubs/iemhacks_DEV-G/assets/64251633/aeee8425-b944-47e3-9ca2-ea5220b337ba)

**Comment by ashutoshgithubs** [comment]
Hi @Maxcillius , Thanks for noticing this bug. You are assigned the issue.
