### ISSUE TITLE
BUG: Invalid Email Format in Signup Page and Non-functional About Us Page Link

### ISSUE THREAD

**Issue by Aniket-2504** [ashutoshgithubs/iemhacks_DEV-G#68]
**Dear @ashutoshgithubs ,**

### I discovered two issues on your website that require attention:

1. Signup Page Bug: The signup page currently accepts invalid email formats, allowing users to sign up without the "@" symbol and domain (e.g., ".com"). This bug affects the accuracy of user registrations and can impact data integrity.
 
 I have recorded a video demonstrating this issue for clarity: 

https://github.com/ashutoshgithubs/iemhacks_DEV-G/assets/145179532/8fd5f496-f611-4042-af7c-c6bc475212a2

 2.  About Us Page Link: The "About Us" page link in the footer is not functioning properly, leading to a non-functional page when clicked.

I'm interested in addressing these issues and providing my best effort to resolve them. Ensuring the correctness of email formats in the signup process and fixing the "About Us" page link are essential for maintaining a seamless user experience on your platform.

Please consider assigning me these tasks, and I will work diligently to fix these bugs and enhance the functionality of your website.

### I look forward to hearing from you soon.

**Comment by ashutoshgithubs** [comment]
Hi @Aniket-2504 You are assigned this task. Please complete this issue and raise PR.

**Comment by Aniket-2504** [comment]
Thank you so much @ashutoshgithubs , i will give my best
