### ISSUE TITLE
Add GitHub Desktop Contribution Instructions

### ISSUE THREAD

**Issue by PradnyaGaitonde** [ashutoshgithubs/iemhacks_DEV-G#71]
**Describe the changes that you want to make in the documentation**
A clear and concise description of the changes to be made in documentation
I am interested in contributing to the project by adding detailed instructions on how to contribute using GitHub Desktop.

I believe that by providing clear and comprehensive guidance, we can encourage more contributors to participate in the project, especially those who prefer using GitHub Desktop for their contributions.

Could you please assign me the issue related to adding GitHub Desktop contribution instructions under gssoc24? I am excited about the opportunity to contribute to the project and help streamline the contribution process for others. 

**Significance of the changes made**
describe the effect of these changes
I believe that by providing clear and comprehensive guidance, we can encourage more contributors to participate in the project, especially those who prefer using GitHub Desktop for their contributions.

**Comment by ashutoshgithubs** [comment]
Hi @PradnyaGaitonde You are assigned this task.

**Comment by ashutoshgithubs** [comment]
Hi @PradnyaGaitonde Please raise your PR once. I need to delete your current PR due to the issue created by GitHub bot. Now this issue is resolved. Please raise your PR again. Sorry for inconvenience.

**Comment by PradnyaGaitonde** [comment]
Hi @ashutoshgithubs No issues, raised the PR again.
