### ISSUE TITLE
[BUG] : When we click on facing an issue button it should scroll to top

### ISSUE THREAD

**Issue by PranotiPD** [ashutoshgithubs/iemhacks_DEV-G#76]
**Describe the bug**
When we click on facing an issue button it would be nice if on redirection to contact us page, it would also scroll up to the page so user get to know that they have been redirected.

**To Reproduce**
1. Go to Home page and scroll to bottom
2. Click on facing an issue
3. 3 See error

**Expected behavior**
It should scroll up

**Screenshots**
None

**Additional context**

**Comment by ashutoshgithubs** [comment]
Hi @PranotiPD You can work on this bug. You are assigned this issues.
