### ISSUE TITLE
Github action workflow to greet contributors when they raise an issue or pr

### ISSUE THREAD

**Issue by ChaitanyaAnand1202** [ashutoshgithubs/iemhacks_DEV-G#83]
**Is your feature request related to a problem? Please describe.**
There is a problem in the current workflow where the welcome action is not performed

**Describe the solution you'd like**
An alternate github workflow to handle the same situation

**Describe alternatives you've considered**
Two files to greet contributors when they make a new pr or raise an issue

**Comment by ashutoshgithubs** [comment]
Hi @ChaitanyaAnand1202 , yeah, this thing I observed now. Please  try to resolve this issue asap.

**Comment by ashutoshgithubs** [comment]
@ChaitanyaAnand1202 gitHub shouldn't  greet when code owner should comment anything.

**Comment by ChaitanyaAnand1202** [comment]
ok, i will work on it to debug the code

**Comment by ashutoshgithubs** [comment]
@ChaitanyaAnand1202 Done
